ci: ansible-lint ruff mypy

ansible-playbook *args="":
  uv run ansible-playbook playbook.yaml {{args}}

ansible-lint:
  CI=1 uv run ansible-lint

ruff: ruff-check ruff-format

ruff-check:
  uv run ruff check

ruff-format:
  uv run ruff format --check

mypy:
  uv run mypy .
