# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 3898f26
_src_path: https://github.com/vivienm/copier-copier
copyright_holder: Vivien Maisonneuve
copyright_year: 2024
forge: github
github_repo: copier-ansible
github_user: vivienm
license: MIT
project_description: An opinionated Copier template for Ansible projects.
project_name: Ansible project template
user_name: Vivien Maisonneuve
