# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: fab4684
_src_path: https://github.com/vivienm/copier-copier
author_name: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_year: 2024
github_account: vivienm
hosting_platform: github
license: MIT
project_description: An opinionated Copier template for Ansible playbooks.
project_name: Ansible project template
repo_name: copier-ansible
